apiVersion: v1
kind: Pod
metadata:
  name: sneak-attack
  namespace: team-beta
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
  restartPolicy: Never