apiVersion: v1
kind: Pod
metadata:
  name: dryrun-test
  namespace: team-beta
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "500Mi"
  restartPolicy: Never